version: '3.8'

services:
  app:
    build: .
    image: ${DOCKER_IMAGE_NAME:-modern-start-page}
    container_name: ${DOCKER_IMAGE_NAME:-modern-start-page}
    ports:
      - "${DOCKER_PORT:-4000}:4000"
    volumes:
      - ${CONFIG_DIR:-./data}:/app/data
    environment:
      - PORT=4000
      - HOST=0.0.0.0
    restart: unless-stopped 